# Generated by Django 5.0.7 on 2024-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='Новостройка'),
            preserve_default=False,
        ),
    ]
