# Generated by Django 5.0.7 on 2024-08-03 14:25

import phonenumbers
from django.db import migrations


def fill_owner_pure_phone_field(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    pure_number_len = 12
    for flat in Flat.objects.all():
        try:
            phone_number = phonenumbers.parse(
                flat.owners_phonenumber, "RU"
            )
        except phonenumbers.phonenumberutil.NumberParseException:
            phone_number = phonenumbers.parse("+70000000000", "RU")

        if not phonenumbers.is_possible_number(phone_number):
            normalized_number = phonenumbers.format_number(
                phone_number, phonenumbers.PhoneNumberFormat.E164
            )
            for _ in range(pure_number_len - len(normalized_number)):
                normalized_number += "0"
        else:
            normalized_number = phonenumbers.format_number(
                phone_number, phonenumbers.PhoneNumberFormat.E164
            )

        flat.owner_pure_phone = normalized_number
        flat.save(update_fields=["owner_pure_phone"])


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_field),
    ]
