# Generated by Django 5.0.7 on 2024-08-03 14:25

import phonenumbers
from django.db import migrations


def fill_owner_pure_phone_field(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        try:
            normalized_number = phonenumbers.parse(
                flat.owners_phonenumber, "RU"
            )
        except phonenumbers.phonenumberutil.NumberParseException:
            normalized_number = phonenumbers.parse("+70000000000", "RU")

        flat.owner_pure_phone = phonenumbers.format_number(
            normalized_number, phonenumbers.PhoneNumberFormat.E164
        )
        flat.save(update_fields=["owner_pure_phone"])


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_field),
    ]
