# Generated by Django 5.0.7 on 2024-08-03 14:25

import phonenumbers as ph
from django.db import migrations


def fill_owner_pure_phone_field(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        try:
            phone_number = ph.parse(flat.owners_phonenumber, "RU")
        except ph.phonenumberutil.NumberParseException:
            phone_number = ph.parse("123", "RU")

        if ph.is_valid_number(phone_number):
            normalized_number = ph.format_number(
                phone_number, ph.PhoneNumberFormat.E164
            )
        else:
            normalized_number = ""

        flat.update(owner_pure_phone=normalized_number)


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone_field),
    ]
