# Generated by Django 5.0.7 on 2024-08-03 15:34

from django.db import migrations


def transfer_owner_to_new_model(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_owner"),
    ]

    operations = [
        migrations.RunPython(transfer_owner_to_new_model),
    ]
