# Generated by Django 5.0.7 on 2024-08-03 17:01

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for owner in Owner.objects.all():
        owner.flat.set(
            Flat.objects.filter(
                owner=owner.full_name, owner_pure_phone=owner.pure_phonenumber
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20240803_1956'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats),
    ]
